=begin
#TextMagic API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TextMagic::ImportColumnMappingItem
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ImportColumnMappingItem' do
  before do
    # run before each test
    @instance = TextMagic::ImportColumnMappingItem.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImportColumnMappingItem' do
    it 'should create an instance of ImportColumnMappingItem' do
      expect(@instance).to be_instance_of(TextMagic::ImportColumnMappingItem)
    end
  end
  describe 'test attribute "column_position_in_file"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "field_or_custom_field_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
